# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_0ebae66f1afd751219fd8c7105c8ed845ef9c265

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,controllers,models,helpers,config,middlewares,routes

# Coverage report path (frontend and backend)
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info, coverage/backend/lcov.info

# Limit analysis to Javascript files in the specified sources
sonar.inclusions=**/*.js

sonar.test.inclusions=**/test/**, **/**.test.js, **/**.spec.js
