# Xenos Fiorenzo Anong, A0257672U

name: "Security Testing"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Mon 00:00

jobs:
  sast-trivy:
    # adapted from example code here: https://github.com/marketplace/actions/aqua-security-trivy
    name: SAST - Trivy code scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"

  dast-zap:
    name: DAST - ZAP scan
    runs-on: ubuntu-latest
    env:
      MONGO_URL: mongodb://localhost:27017
      DEV_MODE: development
      JWT_SECRET: SOMESECRET123456
      BRAINTREE_MERCHANT_ID: hmrc3kfrt2xrvtvp
      BRAINTREE_PUBLIC_KEY: d3rnqcjwn7zk4fpt
      BRAINTREE_PRIVATE_KEY: 767ed9ddd903781349d4c2af441f8eaa
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          npm install
          echo "PORT: 6060" >> .env

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: "6.0"

      - name: Run app
        run: |
          npx kill-port --port 6060
          npm run dev &

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "http://localhost:3000"

  jest-security:
    name: Jest Security Test Cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run Jest tests (security)
        run: npm run test:security
